version: '2'

# make sure to create the external network showroom with: docker network create showroom
networks:
  default:
    name: showroom
    
services:
  optimize-elasticsearch:
    container_name: optimize-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.1
    mem_limit: 2g
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-logs:/usr/share/elasticsearch/logs
      - elasticsearch-tmp:/usr/share/elasticsearch/tmp
    restart: always
    depends_on:
      - cambpm


  optimize-jetty:
    image: registry.camunda.cloud/team-consulting/optimize/optimize-jetty:latest
    #image: registry.camunda.cloud/optimize:3.0.0 - has no license included, consulting one does
    #build: /users/felix/projects/docker/optimize/optimize-jetty
    environment:
      - OPTIMIZE_CAMUNDABPM_REST_URL=http://cambpm:8080/engine-rest
      - OPTIMIZE_ELASTICSEARCH_HOST=optimize-elasticsearch
      - OPTIMIZE_CAMUNDA_BPM_EVENT_IMPORT_ENABLED=true
      - OPTIMIZE_EVENT_BASED_PROCESSES_IMPORT_ENABLED=true
      - OPTIMIZE_EVENT_BASED_PROCESSES_USER_IDS=['demo']
      - OPTIMIZE_EVENT_INGESTION_ACCESS_TOKEN=mytoken
    ports:
      - "8090:8090"
    mem_limit: 2g
    depends_on:
      - optimize-elasticsearch
    restart: always

  cambpm:
    container_name: cambpm
    #image: cambpm
    build: ./
    ports:
      - "8080:8080"
    mem_limit: 2g
    restart: always
    depends_on:
      - db-camunda
      - db-domain
    environment:
      - JAVA_OPTS=-Xmx1024m
      - camunda.datasource.url=jdbc:postgresql://db-camunda:5432/camunda-data
      - domain.datasource.url=jdbc:postgresql://db-domain:5432/domain-data
      - spring.jpa.properties.hibernate.hbm2ddl.auto=create
      
  db-camunda:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=camunda-data"
  db-domain:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=domain-data"
  adminer:
    image: adminer
    ports:
      - "8087:8080"
      
      
##### K A F K A #####

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper
    ports: 
    - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
    - zookeeper-data:/data

  kafka:
    image: confluentinc/cp-kafka:6.0.1
    hostname: kafka
    ports: 
    - "29092:29092"
    depends_on:
    - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
    - kafka-data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:6.0.1
    hostname: schema-registry
    ports:
    - "38081:38081"
    depends_on:
    - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:38081
      SCHEMA_REGISTRY_DEBUG: "true"

  kafka-rest:
    image: confluentinc/cp-kafka-rest:6.0.1
    hostname: kafka-rest
    ports:
    - "38082:38082"
    depends_on:
      - schema-registry
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      KAFKA_REST_SCHEMA_REGISTRY_URL: schema-registry:38081
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://kafka-rest:38082
 
#####  E N D  K A F K A #####
volumes:
  elasticsearch-data:
  elasticsearch-logs:
  elasticsearch-tmp:
  zookeeper-data:
  kafka-data:


