#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring:
  profiles:
    active: default
    include: @spring.profile.from.maven@
  jpa:
    hibernate:
      ddl-auto: create
      hbm2ddl.auto: create   
    show-sql: true
    generate-ddl: true
  kafka:
    bootstrap-servers: localhost:9092
#    producer:
#      transaction-id-prefix: tx-
#      properties:
#        enable.idempotence: true
#        transactional.id: tran-id-1
    consumer:
      group-id: group-1
      enable-auto-commit: false
      isolation-level: read_committed
camunda:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camunda-data
    username: postgres
    password: postgres
    configuration.maximum-pool-size: 30
domain:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/domain-data
    username: postgres
    password: postgres
    configuration.maximum-pool-size: 30   
    
camunda.bpm.admin-user:
  id: demo
  password: demo
  
mail:
  from: demo@camunda.com
  username: 75e6bb70d2864e
  password: ddf1b8e90fb254
  smtp:
    host: smtp.mailtrap.io
    port: 2525
    
azure:
  storage:
    accountName: hrdemo
    connectionString: paste_here_from_your_storage_access_settings